apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: gautam018/userservice:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
            protocol: TCP
        env:
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: PARENT_DB
            value: "freeFood"
          - name: USER_FLASK_PORT
            value: "8081"
          - name: KAFKA_HOST
            value: "kafka.pinot-quickstart"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ORDERS_TOPIC
            value: "orders"
          
          
          
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 8081
  type: LoadBalancer
