apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: email
spec:
  selector:
    matchLabels:
      app: email
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: gautam018/emailconsumer:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8083
            protocol: TCP
        env:
          - name: KAFKA_HOST
            value: "kafka.pinot-quickstart"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ORDERS_TOPIC
            value: "orders"
          
          
          
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  type: NodePort
  selector:
    app: email
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    targetPort: 8083